blog/urls.py
from django.urls import include, path
from .views import (
    blog_list_view,
    blog_detail_view,
    blog_create_view,
    blog_update_view,
    blog_upload_gallery_images_view,
)

urlpatterns = [
    path("article/<int:pk>", blog_detail_view, name="blog-detail"),
    path("articles", blog_list_view, name="blog-list"),
    path("article/add", blog_create_view, name="blog-create"),
    path("article/<int:pk>/edit", blog_update_view, name="blog-update"),
    path(
        "article/<int:pk>/add_images",
        blog_upload_gallery_images_view,
        name="blog-upload-images",
    ),
]

app_name = "blog"

hobbysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("commissions/", include("commissions.urls", namespace="commissions")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("wiki/", include("wiki.urls", namespace="wiki")),
    path("merchstore/", include("merchstore.urls", namespace="merchstore")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("profile/", include("user_management.urls", namespace="user-management")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchstore/urls.py
from django.urls import path

from .views import product_list, product_detail, product_create, product_update, cart_list, transaction_list


urlpatterns = [
    path('items', product_list, name = 'list'),
    path('item/<int:pk>', product_detail, name = 'detail'),
    path("item/add", product_create, name = "product_create"),
    path("item/<int:pk>/edit", product_update, name = "product_edit"),
    path("cart", cart_list, name="cart"),
    path("transactions", transaction_list, name="transaction"),
]

app_name = "merchstore"

merchstore/models.py
from django.db import models
from django.urls import reverse

from user_management.models import Profile


class ProductType(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return "{}".format(self.name)

    class Meta:
        ordering = ["name"]


class Product(models.Model):
    name = models.CharField(max_length=255)
    type = models.ForeignKey(
        ProductType, null=True, on_delete=models.SET_NULL, related_name="products"
    )
    owner = models.ForeignKey(
        Profile, null=True, on_delete=models.CASCADE, related_name="products_owned"
    )
    description = models.TextField()
    price = models.DecimalField(decimal_places=2, max_digits=50)
    stock = models.PositiveIntegerField(default=0)
    AVAILABLE = "AV"
    ON_SALE = "SA"
    OUT_OF_STOCK = "OOS"
    STATUS_CHOICES = [
        (AVAILABLE, "Available"),
        (ON_SALE, "On Sale"),
        (OUT_OF_STOCK, "Out of Stock"),
    ]
    status = models.CharField(
        max_length=50, choices=STATUS_CHOICES, default=AVAILABLE)

    def __str__(self):
        return "{}".format(self.name)

    def get_absolute_url(self):
        return reverse("merchstore:detail", args=[str(self.pk)])

    def get_status(self):
        return self.status

    class Meta:
        ordering = ["name", "status"]


class Transaction(models.Model):
    buyer = models.ForeignKey(
        Profile, null=True, on_delete=models.SET_NULL, related_name="products_bought"
    )
    product = models.ForeignKey(
        Product, null=True, on_delete=models.SET_NULL, related_name="buyers"
    )
    amount = models.PositiveIntegerField()
    ON_CART = "OC"
    TO_PAY = "TP"
    TO_SHIP = "TS"
    TO_RECEIVE = "TR"
    DELIVERED = "D"
    STATUS_CHOICES = (
        (ON_CART, "On Cart"),
        (TO_PAY, "To Pay"),
        (TO_SHIP, "To Ship"),
        (TO_RECEIVE, "To Receive"),
        (DELIVERED, "Delivered")
    )
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default=ON_CART)
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{ self.buyer } bought {self.amount} - {self.product} item/s'
    
    # def get_status(self):
    #     return self.status

    def save(self, *args, **kwargs):
        self.product.stock -= self.amount
        self.product.save()
        super().save(*args, **kwargs)

    class Meta:
        ordering = ["status"]

merchstore/forms.py
from django import forms

from .models import Product, Transaction


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["name", "type", "description", "price", "stock", "status"]


class TransactionForm(forms.ModelForm):
    def __init__(self, *args, product=None, **kwargs):
        self.product = product
        super().__init__(*args, **kwargs)

    class Meta:
        model = Transaction
        fields = ["amount"]

    def clean_amount(self, *args, **kwargs):
        print(args)
        amount = self.cleaned_data.get("amount")
        if amount <= 0:
            raise forms.ValidationError("Please choose a positive amount")
        if amount > self.product.stock:
            raise forms.ValidationError("Not enough stock")
        return amount

merchstore/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Product, Transaction
from .forms import ProductForm, TransactionForm


def product_list(request):
    user_products = []
    all_products = []
    if request.user.is_authenticated:
        user = request.user.profile
        user_products = Product.objects.filter(
            owner__username=request.user.profile.username)
        all_products = Product.objects.exclude(
            owner__username=request.user.profile.username)
    else:
        all_products = Product.objects.all()

    ctx = {
        'user_products': user_products,
        "all_products": all_products
    }
    return render(request, "merchstore/product_list.html", ctx)


def product_detail(request, pk):
    product = Product.objects.get(pk=pk)
    transaction_form = TransactionForm()
    if request.method == "POST":
        transaction_form = TransactionForm(request.POST, product=product)
        if transaction_form.is_valid():
            transaction = transaction_form.save(commit=False)
            transaction.product = product
            if product.stock == 0:
                product.status = Product.OUT_OF_STOCK
            product.save(update_fields=["stock", "status"])
            if request.user.is_authenticated:
                transaction.buyer = request.user.profile
            else:
                return redirect("login")
            transaction.save()
            return redirect("merchstore:cart")

    ctx = {
        "product": product,
        "form": transaction_form,
    }
    return render(request, "merchstore/product_detail.html", ctx)


@login_required
def product_create(request):
    user = request.user.profile
    product_form = ProductForm()
    if request.method == "POST":
        product_form = ProductForm(request.POST)
        if product_form.is_valid():
            product = product_form.save()
            product.owner = user
            if product.stock == 0:
                product.status = Product.OUT_OF_STOCK
            product.save()
            return redirect("merchstore:detail", pk=product.pk)

    ctx = {
        "form": product_form,
        "user": user
    }
    return render(request, "merchstore/product_create.html", ctx)


@login_required
def product_update(request, pk):
    product = Product.objects.get(pk=pk)
    user = request.user.profile
    if request.method == "POST":
        product_form = ProductForm(request.POST, instance=product)
        if product_form.is_valid():
            product.owner = user
            if product.stock == 0:
                product.status = Product.OUT_OF_STOCK
            product_form.save()
            return redirect("merchstore:detail", pk=product.pk)
    else:
        product_form = ProductForm(instance=product)

    ctx = {
        "form": product_form,
        "product": product,
        "user": user
    }
    return render(request, "merchstore/product_update.html", ctx)


@login_required
def cart_list(request):
    user = request.user.profile
    cart = Transaction.objects.filter(buyer=user).order_by("product__owner")
    ctx = {
        "user": user,
        "cart": cart
    }
    return render(request, "merchstore/cart.html", ctx)


@login_required
def transaction_list(request):
    user = request.user.profile
    transactions = Transaction.objects.filter(
        product__owner=user).order_by("buyer__user")
    ctx = {
        "user": user,
        "transactions": transactions
    }
    return render(request, "merchstore/transactions.html", ctx)

templates/merchstore/baase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Hobby site </title>
</head>
<body>
	<h1> Merchandise Store </h1>
    {% if request.user.is_authenticated %}
        <h3> Welcome {{ request.user.username }}! </h3>
        <form action="{% url 'logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit">LOG OUT</button>
        </form>
    {% else %}
        <h3> Hello guest! </h3>
        <a href="{% url 'login' %}"> LOGIN HERE </a>
        <br>
    {% endif %}

	{% block content %}
	{% endblock %}
</body>
</html>

templates/merchstore/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Hobby site </title>
</head>
<body>
	<h1> Merchandise Store </h1>
    {% if request.user.is_authenticated %}
        <h3> Welcome {{ request.user.username }}! </h3>
        <form action="{% url 'logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit">LOG OUT</button>
        </form>
    {% else %}
        <h3> Hello guest! </h3>
        <a href="{% url 'login' %}"> LOGIN HERE </a>
        <br>
    {% endif %}

	{% block content %}
	{% endblock %}
</body>
</html>

templates/merchstore/cart.html
{% extends 'base.html' %}
{% block content %}
<br>
<a href="{% url 'merchstore:list' %}">BACK TO PRODUCT LIST</a>
{% if request.user.is_authenticated %}
<h1>Your Cart</h1>
<ul> 
    {% for transaction in cart %}
    <li>
        <h3> Product:         
        <a href="{% url 'merchstore:detail' pk=transaction.product.pk %}">{{ transaction.product.name }}</a>
        </h3>
        Pieces: {{ transaction.amount }}
        <br>
        Seller: {{ transaction.product.owner.user }}
        <br>
        Date of purchase: {{ transaction.created_on }}
        <br>
        Status: {{ transaction.get_status_display }}
    </li>
    {% endfor %}
    </ul>
{% else %}
    <h3> Log in to access your cart. </h3>
    <a href="{% url 'login' %}"> LOGIN HERE </a>
    <br>
{% endif %}
{% endblock %}

templates/merchstore/product_create.html
{% extends 'base.html' %}
{% block content %}
<br>
<a href="{% url 'merchstore:list' %}">BACK TO PRODUCT LIST</a>
<h1>Create a Product</h1>
{% if request.user.is_authenticated %}
Seller: {{ request.user }}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">CREATE</button>
</form>
{% else %}
<p>Please <a href="{% url 'login' %}">log in</a> to add a product.</p>
{% endif %}
{% endblock %}

templates/merchstore/product_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="peach-bg" style="height: 100vh"> 


    {% if user != "Anonymous" %}
        <br>
        <div class="merch-icons">
            <a href="{% url 'merchstore:cart' %}"> <i class="fa-solid fa-cart-shopping merch-icons hover"></i> </a>
            <a href="{% url 'merchstore:transaction' %}"> <i class="fa-solid fa-credit-card merch-icons hover"></i> </a> 
        </div>
        
        <div class="center merch-detail-bg">
            <h3 class="lowercase orange" style="padding-left: 10px; margin-bottom: 6px"> {{ product.type }} </h3>
            <div class="merch-header-container">
                <div>
                    <h3 class="white"> {{ product.name }} </h3>
                </div>
                
                <div> 
                    <h3 class="light-gray"> P {{product.price }} </h3>
                </div>
        </div>

        <br>
        <div class="merch-description-container">
            <p>owner</p> <p>{{ product.owner.user }}</p>
            <p>description</p> <p> {{ product.description }} </p>
            <p>status</p> <p>{{ product.get_status_display }}</p>
            <p>stock</p> <p>{{ product.stock }}</p>
        </div>

        {% if user == product.owner.user %}
            <h2> <a class="update" href="{% url 'merchstore:product_edit' pk=product.pk %}">update product</a> </h2>
        {% else %}
            <div style="padding-left: 10px">
                <form method="POST">
                    {% csrf_token %}
                    {{ form }}
                    {% if product.stock == 0 %}
                        <button disabled>BUY</button>
                    {% else %}
                        <div class="center-text" style="padding-top: 30px">
                            <button class="merch-buy">BUY</button>
                        </div>
                    {% endif %}
                </form>
            </div>
        {% endif%}

        <a href="{% url 'merchstore:list' %}"> <button class="back merch-back"> Back </button> </a>
        </div>
        
    {% else %}
        <p>Please <a href="{% url 'login' %}">log in</a> to purchase this product.</p>
    {% endif %}

</div>


{% endblock %}

templates/merchstore/product_list.html
{% extends 'base.html' %}
{% block content %}

{% if request.user.is_authenticated %}
    <div class="merch-icons">
        <a href="{% url 'merchstore:cart' %}"> <i class="fa-solid fa-cart-shopping merch-icons hover"></i> </a>
        <a href="{% url 'merchstore:transaction' %}"> <i class="fa-solid fa-credit-card merch-icons hover"></i> </a> 
    </div>
{% endif %}

<div class="peach-bg center-text" style="padding-top: 150px; height: 330px"> 
    <p class="header"> MERCHANDISE STORE </p> 
</div>

<div class="center" style="width: 700px;">
    {% if request.user.is_authenticated %}
        <div class="list-item merch">
            <h3>your products</h3>
            
            {% for product in user_products %}
                <div class="center">
                <a href="{% url 'merchstore:detail' pk=product.pk %}"> <button class="merch">{{ product.name }} </button> </a> 
                </div>
            {% endfor %}
            
        </div>

        <div class="create-link center-text">
            <a href="{% url 'merchstore:product_create' %}">add a product</a>
        </div>

        <div class="list-item merch">
            <h3>all products</h3>
                {% for product in all_products %}
                    <div class="center">
                        <a href="{% url 'merchstore:detail' pk=product.pk %}">  <button class="merch"> {{ product.name }} </button> </a>
                    </div>
                {% endfor %}
        </div>

    {% else %}
        <div class="list-item merch">
            <h3>all products </h3>
                {% for product in all_products %}
                <div class="center">
                    <a href="{% url 'merchstore:detail' pk=product.pk %}">  <button class="merch"> {{ product.name }} </button> </a>
                </div>
                {% endfor %}
        </div>
    {% endif %}
</div>

{% endblock %}

templates/merchstore/product_update.html
{% extends 'base.html' %}
{% block content %}
<br>
<a href="{% url 'merchstore:list' %}">BACK TO PRODUCT LIST</a>
<h1>Product</h1>
<b>Currently Editing: </b>{{ product.name }}
<br>
Seller: {{ request.user }}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <button type="submit">UPDATE</button>
</form>
{% endblock %}

templates/merchstore/transactions.html
{% extends 'base.html' %}
{% block content %}
<br>
<a href="{% url 'merchstore:list' %}">BACK TO PRODUCT LIST</a>
<h1>Your Transactions</h1>
    {% for transaction in transactions %}
    {% if transaction.product.owner != transaction.buyer %}
    <h3> Product:         
    <a href="{% url 'merchstore:detail' pk=transaction.product.pk %}">{{ transaction.product.name }}</a>
    </h3>
    <b> Pieces: {{ transaction.amount }} </b>
    <br>
    Sold to: {{ transaction.buyer.user }}
    <br>
    Date of purchase: {{ transaction.created_on }}
    <br>
    Status: {{ transaction.get_status_display }}
    {% endif %}
    <br>
    {% endfor %}
{% endblock %}