blog/urls.py
from django.urls import include, path
from .views import (
    blog_list_view,
    blog_detail_view,
    blog_create_view,
    blog_update_view,
    blog_upload_gallery_images_view,
)

urlpatterns = [
    path("article/<int:pk>", blog_detail_view, name="blog-detail"),
    path("articles", blog_list_view, name="blog-list"),
    path("article/add", blog_create_view, name="blog-create"),
    path("article/<int:pk>/edit", blog_update_view, name="blog-update"),
    path(
        "article/<int:pk>/add_images",
        blog_upload_gallery_images_view,
        name="blog-upload-images",
    ),
]

app_name = "blog"

hobbysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("commissions/", include("commissions.urls", namespace="commissions")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("wiki/", include("wiki.urls", namespace="wiki")),
    path("merchstore/", include("merchstore.urls", namespace="merchstore")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("profile/", include("user_management.urls", namespace="user-management")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiki/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import (
    article_list_view,
    article_detail_view,
    article_update_view,
    article_create_view,
    article_upload_image_view,
)

urlpatterns = [
    path("articles", article_list_view, name="article-list"),
    path("article/<int:pk>", article_detail_view, name="article-detail"),
    path("article/<int:pk>/edit", article_update_view, name="article-update"),
    path("article/add", article_create_view, name="article-create"),
    path(
        "article/<int:pk>/add_images",
        article_upload_image_view,
        name="article-upload-images",
    ),
]

app_name = "wiki"

wiki/models.py
from django.db import models
from django.urls import reverse
from user_management.models import Profile


class ArticleCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return str(self.name)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Article categories"


class Article(models.Model):
    title = models.CharField(max_length=255)
    entry = models.TextField()
    category = models.ForeignKey(
        ArticleCategory, on_delete=models.SET_NULL, null=True, related_name="articles"
    )
    author = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, related_name="articles"
    )
    header_image = models.ImageField(
        upload_to="images/", null=False, default="default.jpg"
    )
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("wiki:article-detail", args=[str(self.pk)])


class Comment(models.Model):
    author = models.ForeignKey(
        Profile, on_delete=models.SET_NULL, null=True, related_name="comments"
    )
    article = models.ForeignKey(
        Article, on_delete=models.SET_NULL, null=True, related_name="comments"
    )
    entry = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]


class ArticleImage(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name="images"
    )
    image = models.FileField(upload_to="images/", null=False)

wiki/forms.py
from django import forms
from .models import Article, Comment


class ArticleCreateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "entry", "category", "header_image"]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["entry"]


class ArticleImagesForm(forms.Form):
    images = forms.FileField(
        widget=forms.TextInput(
            attrs={
                "name": "images",
                "type": "file",
                "class": "form-control",
                "multiple": "true",
            }
        )
    )

wiki/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Article, ArticleCategory, Comment, ArticleImage
from .forms import ArticleCreateForm, CommentForm, ArticleImagesForm


def article_list_view(request):
    categories = ArticleCategory.objects.all()
    articles = Article.objects.all()
    ctx = {"categories": categories, "articles": articles}
    return render(request, "wiki/wiki_list.html", ctx)


@login_required
def article_detail_view(request, pk):
    category = ArticleCategory.objects.all()
    all_articles = Article.objects.all()
    comments = Comment.objects.all()
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment()
            comment.author = request.user.profile
            comment.article = Article.objects.get(pk=pk)
            comment.entry = form.cleaned_data.get("entry")
            comment.save()
            form = CommentForm()
    ctx = {
        "article": Article.objects.get(pk=pk),
        "categories": category,
        "all_articles": all_articles,
        "comments": comments,
        "form": form,
    }
    return render(request, "wiki/wiki_detail.html", ctx)


@login_required
def article_update_view(request, pk):
    article = Article.objects.get(pk=pk)
    form = ArticleCreateForm()

    if request.method == "POST":
        image_form = ArticleImagesForm(request.POST, request.FILES)
        form = ArticleCreateForm(request.POST, request.FILES)
        if form.is_valid():
            article.title = form.cleaned_data.get("title")
            article.entry = form.cleaned_data.get("entry")
            article.category = form.cleaned_data.get("category")
            article.header_image = form.cleaned_data.get("header_image")
            article.save()

            return redirect("wiki:article-detail", pk=pk)
    ctx = {"form": form, "article": article}
    return render(request, "wiki/wiki_update.html", ctx)


@login_required
def article_create_view(request):
    form = ArticleCreateForm()
    image_form = ArticleImagesForm()

    if request.method == "POST":
        image_form = ArticleImagesForm(request.POST, request.FILES)
        form = ArticleCreateForm(request.POST, request.FILES)
        if form.is_valid():
            article = Article()
            article.author = request.user.profile
            article.title = form.cleaned_data.get("title")
            article.entry = form.cleaned_data.get("entry")
            article.category = form.cleaned_data.get("category")
            article.header_image = form.cleaned_data.get("header_image")
            article.save()

            images = request.FILES.getlist("images")
            for image in images:
                imageobj = ArticleImage()
                imageobj.article = article
                imageobj.image = image
                imageobj.save()

            return redirect("wiki:article-list")

    ctx = {"form": form, "image_form": image_form}
    return render(request, "wiki/wiki_create.html", ctx)


@login_required
def article_upload_image_view(request, pk):
    images_form = ArticleImagesForm()
    article = Article.objects.get(pk=pk)

    if request.method == "POST":
        images_form = ArticleImagesForm(request.POST, request.FILES)
        images = request.FILES.getlist("images")
        for image in images:
            imageobj = ArticleImage()
            imageobj.article = article
            imageobj.image = image
            imageobj.save()

        return redirect("wiki:article-detail", pk=pk)
    ctx = {
        "images_form": images_form,
        "article": article,
    }

    return render(request, "wiki/wiki_upload_images.html", ctx)


# Create your views here.

templates/wiki/wiki_create.html
{% extends 'base.html' %}

{% block content %}
    <body>
        <h1> Add new article? </h1>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_div }}
            {{ image_form.as_div }}

            <input type="submit" value="Submit">
        </form>
    </body>
{% endblock %}

templates/wiki/wiki_detail.html
{% extends 'base.html' %}
{% block app %} Wiki {% endblock %}
{% block styles %}
    <style>
        .gallery {
            display: grid;
            grid-template-columns: 210px 210px 210px;
            gap: 8px;
            margin: 5px;
            height: auto;
        }
        .gallery-item > img {
            width: 100%;
            height: 100%;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="white-divider"> </div>
    <div class="article center">
        <div class="article-header header"> 
            <div>
                <h2 class="category"> {{ article.category }} </h2>
                <h2 class="title"> {{ article.title }} </h2> 
            </div>
            <div>
                <h2 class="author bottom"> {{ article.author }} </h2>
                <h2 class="create-date bottom"> {{ article.created_on }} </h2>
            </div>
        </div>

        <img class="header-img" src="{{ article.header_image.url }}"></img>
        <p> {{ article.entry }} </p>
        <!-- <p> Last updated on: {{ article.updated_on }}</p> -->

        {% if article in request.user.profile.articles.all %}
            <div class="create-link">
                <a href="{% url 'wiki:article-update' pk=article.pk %}"> Edit this article? </a>
            </div>  
        {% endif %}
        

            
        <div class="category" style="font-size: 30px;"> gallery </div>
        <div class="thin-line-divider"> </div>
        <div class="gallery">
            {% for imageobj in article.images.all %}
                <div class="gallery-item"> <img src="{{ imageobj.image.url }} "> </div>
            {% endfor %}
        </div>
        {% if article in request.user.profile.articles.all %}
        <div class="create-link"> <a href="{% url 'wiki:article-upload-images' pk=article.pk %}"> Upload more images? </a> </div>
        {% endif %}


        <div class="white-divider"></div>
        <div class="category" style="font-size: 30px;"> comments </div>
        <div class="thin-line-divider"> </div>
        <div class="comment-section">
            {% for commentobj in article.comments.all %}
                <p> {{ commentobj.author }}: {{ commentobj.entry }} </p>
            {% endfor %}
            <form method="POST">
                {% csrf_token %}
                {{ form.as_div }}
                <button type="submit"> Submit </button>
            </form>
        </div>

        <div class="white-divider"></div>
    </div>

    {% if request.user.is_authenticated %}
    <div class="article-recommendations">
            <p class="category" style="text-transform: none; margin-bottom: 30px;"> Read more {{ article.category }} articles </p>
            <div class="recommendation-grid"> 
            {% for other_article in article.category.articles.all %}
                {% if other_article != article %}
                <p class="recommendation-grid-item"> <a href="{{ other_article.get_absolute_url }}"> {{ other_article }} </a> </p>
                {% endif %}
            {% endfor %}
            </div>
            </ul>
        {% endif %}
    </div>

    <a href="{% url 'wiki:article-list' %}"> <button class="back"> Back? </button> </a>

{% endblock%}

templates/wiki/wiki_list.html
{% extends 'base.html' %}
{% block app %} Wiki {% endblock %}
{% block content %}

<div class="peach-bg"> 
    <h1 class="header">  WIKI  </h1>
</div>


<div class="grid-container center">
    {% if request.user.is_authenticated %}
        <div class="list-item bold-black">
            <h3> My Articles </h3>
            <ul>
            {% for article in request.user.profile.articles.all %}
                <li>
                    <a href="{{ article.get_absolute_url }}">  {{ article }} </a>
                </li>
            {% endfor %}
            </ul>
        </div>
    {% endif %} 

    {% for category in categories %}
        <div class="list-item">
            <h3> {{ category }} </h3>   
            <ul>
                {% for article in category.articles.all %}
                    {% if request.user.is_authenticated %}
                        {% if article not in request.user.profile.articles.all %}
                        <li>  <a href="{{ article.get_absolute_url }}"> {{ article }} </a> </li>
                        {% endif %}
                    {% else %}
                        <li> <a href="{{ article.get_absolute_url }}"> {{ article }} </a></li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
</div>

<div class="center create-link">
    {% if request.user.is_authenticated %}
    <h2> <a href="{% url 'wiki:article-create' %}"> Create new article? </a></h2>
    {% endif %} 
</div>
{% endblock %}

templates/wiki/wiki_update.html
{% extends 'base.html' %}
{% block app %} Wiki {% endblock%}
{% block content %}
    <body>
        <h3> You are updating {{ article }} </h3>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Submit">
        </form>
    </body>
{% endblock %}

templates/wiki/wiki_upload_images.html
{% extends 'base.html' %}
{% block app %} Wiki {% endblock %}
{% block content %}
<h3> Upload images for {{article}} </h3>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ images_form.as_div }}
    <button type="submit"> Upload </button>
</form>
{% endblock %}