blog/urls.py
from django.urls import include, path
from .views import (
    blog_list_view,
    blog_detail_view,
    blog_create_view,
    blog_update_view,
    blog_upload_gallery_images_view,
)

urlpatterns = [
    path("article/<int:pk>", blog_detail_view, name="blog-detail"),
    path("articles", blog_list_view, name="blog-list"),
    path("article/add", blog_create_view, name="blog-create"),
    path("article/<int:pk>/edit", blog_update_view, name="blog-update"),
    path(
        "article/<int:pk>/add_images",
        blog_upload_gallery_images_view,
        name="blog-upload-images",
    ),
]

app_name = "blog"

commissions/urls.py
from django.urls import path

from .views import commission_create, commission_detail, commission_list, commission_edit

urlpatterns = [
    path("list", commission_list, name="commission_list"),
    path("detail/<int:pk>", commission_detail, name="commission_detail"),
    path("add", commission_create, name="commission_create"),
    path("<int:pk>/edit", commission_edit, name="commission_create"),
]

app_name = "ledger"

hobbysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("commissions/", include("commissions.urls", namespace="commissions")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("wiki/", include("wiki.urls", namespace="wiki")),
    path("merchstore/", include("merchstore.urls", namespace="merchstore")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("profile/", include("user_management.urls", namespace="user-management")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchstore/urls.py
from django.urls import path

from .views import product_list, product_detail, product_create, product_update, cart_list, transaction_list


urlpatterns = [
    path('items', product_list, name = 'list'),
    path('item/<int:pk>', product_detail, name = 'detail'),
    path("item/add", product_create, name = "product_create"),
    path("item/<int:pk>/edit", product_update, name = "product_edit"),
    path("cart", cart_list, name="cart"),
    path("transactions", transaction_list, name="transaction"),
]

app_name = "merchstore"

user_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from .views import register_view, profile_dashboard, profile_update

urlpatterns = [
    path("", profile_update, name="update"),
    path("dashboard/", profile_dashboard, name="dashboard"),
    path("register/", register_view, name="register"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = "user_management"

wiki/urls.py
from django.urls import path, include
from django.contrib import admin
from .views import (
    article_list_view,
    article_detail_view,
    article_update_view,
    article_create_view,
    article_upload_image_view,
)

urlpatterns = [
    path("articles", article_list_view, name="article-list"),
    path("article/<int:pk>", article_detail_view, name="article-detail"),
    path("article/<int:pk>/edit", article_update_view, name="article-update"),
    path("article/add", article_create_view, name="article-create"),
    path(
        "article/<int:pk>/add_images",
        article_upload_image_view,
        name="article-upload-images",
    ),
]

app_name = "wiki"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block app %} {% endblock %} </title>
    <script src="https://kit.fontawesome.com/f5ef0fbbfb.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css">
    {% block styles %} {% endblock%}
</head>
<body>
    <div class="navbar"> 
        <img src ="{% static 'img/laptop.png' %}"> </img>
        <a id="hobbysite"> hobbysite</a>
        <a class="right" href="{% url 'user_management:dashboard' %}"> profile </a>
        <a class="right" href="{% url 'commissions:commission_list' %}"> commission </a>
        <a class="right" href="{% url 'merchstore:list' %}"> store </a> 
        <a class="right" href="{% url 'blog:blog-list' %}"> blog </a>
        <a class="right" href="{% url 'wiki:article-list' %}"> wiki </a>
    </div>

	{% block content %}
	{% endblock %}

</body>
</html>

templates/commission_detail.html
{% extends "base.html" %}
{% block content %}
	<h1>{{ commission_detail.title }}</h1>
	<p>People required: {{ commission_detail.people_required }}</p>
	<p>Submitted on {{ commission_detail.created_on }}</p>
	<p>Edited on {{ commission_detail.updated_on }}</p>
	<br/>
	<p>{{ commission_detail.description }}</p>
	<br/>
	<h2>Comments</h2>
	{% for comment in commission_detail.comments.all %}
	<p>Created: {{ comment.created_on }}</p>
	<p>Edited: {{ comment.updated_on }}</p>
	<li>{{comment.entry}}</li>
	<br/>
	<br/>
	{% endfor %}
{% endblock%}

templates/commission_list.html
{% extends "base.html" %}
{% block content %}
<ul>
	{% for commission in commission_list %}
	<li>
	<a href="{{commission.get_absolute_url}}">{{commission.title}}</a>
	</li>
	<p>Submitted: {{ commission.created_on }}</p>
	<br/>
	{% endfor %}
</ul>
{% endblock%}

templates/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product Details</title>
</head>
<body>
    <h1> Product: {{ product.name }} </h1>
    <h2> Type: {{ product.type }} </h2>
    <p><b><i> {{product.price }} Pesos </i></b></p>
    <p> {{ product.description }} </p>
</body>
</html>

templates/product_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product List</title>
</head>
<body>
    <h1>Product Types </h1>
    {% for type in types %}
        <h3> {{ type }} </h3>
        <ul>
            {% for product in type.products.all %}
                <li>
                    <a href="{{ product.get_absolute_url }}">
                        {{ product }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% endfor %}
</body>
</html>